export const LISTAR_PROYECTOS='LISTAR_PROYECTOS';
export const BORRAR_PROYECTO_POR_ID='BORRAR_PROYECTO_POR_ID'; 
export const INSERTAR_PROYECTO='INSERTAR_PROYECTO'; //QUE REVUELVA  EL REGISTRO INSERTADO
export const ACTUALIZAR_PROYECTO_POR_ID='ACTUALIZAR_PROYECTO_POR_ID';
//==================PARA GUARDAR PROYECTO=================
export const INSERTAR_PLANTILLA='INSERTAR_PLANTILLA'; //QUE DEVUELVA EL REGISTRO INSERTADO
export const INSERTAR_LISTAMUEBLES='INSERTAR_LISTAMUEBLES' //SE LE MANDARA CONTROLLER UN ARREGLO DE LISTAMUEBLES 
//=============PARA ACTUALIZAR PROYECTO==========
export const ACTUALIZAR_PLANTILLA_POR_ID='ACTUALIZAR_PLANTILLA';
export const BORRAR_LISTAMUEBLES_POR_NOMBRE='BORRAR_LISTAMUEBLES_POR_NOMBRE';
//INSERTAR NUEVOS REGISTROS A LISTAMUEBLES
//==================ABRIR PROYECTO
export const LISTAR_PROYECTO_POR_ID='LISTAR_PROYECTO_POR_ID';
export const LISTAR_PLANTILLA_POR_ID='LISTAR_PLANTILLA_POR_ID';
export const LISTAR_LISTAMUEBLES_POR_NOMBRE='LISTAR_LISTAMUEBLES_POR_NOMBRE'; // JOIN MUEBLES ON CodMueble
export const LISTAR_MUEBLES_POR_LISTAMUEBLES='LISTAR_MUEBLES_POR_LISTAMUEBLES'; //si lo de arriva se puede esto ya no
//=================USUARIO ELIGIENDO MUEBLES=====================
export const LISTAR_CATEGORIAS='LISTAR_CATEGORIAS';
export const LISTAR_SUBCATEGORIAS_POR_CATEGORIA='LISTAR_SUBCATEGORIAS_POR_CATEGORIA';
export const LISTAR_MUEBLES_POR_SUBCATEGORIA='LISTAR_MUEBLES_POR_SUBCATEGORIA'

//==============================================SIGNIN===========
export const GRABAR_USUARIO = 'GRABAR_USUARIO';
export const LISTAR_USUARIOS = 'LISTAR_USUARIOS'